/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as CharacterRouteImport } from './routes/character/route'
import { Route as IndexImport } from './routes/index'
import { Route as CharacterIndexImport } from './routes/character/index'
import { Route as CharacterCharacterDetailIndexImport } from './routes/character/character-detail/index'

// Create/Update Routes

const CharacterRouteRoute = CharacterRouteImport.update({
  id: '/character',
  path: '/character',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const CharacterIndexRoute = CharacterIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CharacterRouteRoute,
} as any)

const CharacterCharacterDetailIndexRoute =
  CharacterCharacterDetailIndexImport.update({
    id: '/character-detail/',
    path: '/character-detail/',
    getParentRoute: () => CharacterRouteRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/character': {
      id: '/character'
      path: '/character'
      fullPath: '/character'
      preLoaderRoute: typeof CharacterRouteImport
      parentRoute: typeof rootRoute
    }
    '/character/': {
      id: '/character/'
      path: '/'
      fullPath: '/character/'
      preLoaderRoute: typeof CharacterIndexImport
      parentRoute: typeof CharacterRouteImport
    }
    '/character/character-detail/': {
      id: '/character/character-detail/'
      path: '/character-detail'
      fullPath: '/character/character-detail'
      preLoaderRoute: typeof CharacterCharacterDetailIndexImport
      parentRoute: typeof CharacterRouteImport
    }
  }
}

// Create and export the route tree

interface CharacterRouteRouteChildren {
  CharacterIndexRoute: typeof CharacterIndexRoute
  CharacterCharacterDetailIndexRoute: typeof CharacterCharacterDetailIndexRoute
}

const CharacterRouteRouteChildren: CharacterRouteRouteChildren = {
  CharacterIndexRoute: CharacterIndexRoute,
  CharacterCharacterDetailIndexRoute: CharacterCharacterDetailIndexRoute,
}

const CharacterRouteRouteWithChildren = CharacterRouteRoute._addFileChildren(
  CharacterRouteRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/character': typeof CharacterRouteRouteWithChildren
  '/character/': typeof CharacterIndexRoute
  '/character/character-detail': typeof CharacterCharacterDetailIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/character': typeof CharacterIndexRoute
  '/character/character-detail': typeof CharacterCharacterDetailIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/character': typeof CharacterRouteRouteWithChildren
  '/character/': typeof CharacterIndexRoute
  '/character/character-detail/': typeof CharacterCharacterDetailIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/character' | '/character/' | '/character/character-detail'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/character' | '/character/character-detail'
  id:
    | '__root__'
    | '/'
    | '/character'
    | '/character/'
    | '/character/character-detail/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CharacterRouteRoute: typeof CharacterRouteRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CharacterRouteRoute: CharacterRouteRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/character"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/character": {
      "filePath": "character/route.tsx",
      "children": [
        "/character/",
        "/character/character-detail/"
      ]
    },
    "/character/": {
      "filePath": "character/index.tsx",
      "parent": "/character"
    },
    "/character/character-detail/": {
      "filePath": "character/character-detail/index.tsx",
      "parent": "/character"
    }
  }
}
ROUTE_MANIFEST_END */
